# Generated by Django 5.2.7 on 2025-11-02 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='track',
        ),
        migrations.RemoveField(
            model_name='trackingpackage',
            name='track',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='track',
        ),
        migrations.AddField(
            model_name='complaint',
            name='label',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackingpackage',
            name='label',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.label'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
