# Generated by Django 5.2.7 on 2025-11-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_label_track_remove_trackingpackage_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingpackage',
            name='Arrived_new_location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingpackage',
            name='Arrived_new_location_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
