# Generated by Django 5.2.7 on 2025-11-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trackingpackage_arrived_new_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingpackage',
            old_name='Arrived_new_location',
            new_name='new_location',
        ),
        migrations.RemoveField(
            model_name='trackingpackage',
            name='Arrived_new_location_date',
        ),
        migrations.AddField(
            model_name='trackingpackage',
            name='new_location_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
