# Generated by Django 5.2.7 on 2025-11-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_arrived_new_location_trackingpackage_new_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonealert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField()),
                ('tracking_id', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
