# Generated by Django 5.2.7 on 2025-11-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_phonealert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonealert',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
