# Generated by Django 5.2.7 on 2025-11-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_phonealert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonealert',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='phonealert',
            name='tracking_id',
            field=models.CharField(max_length=50),
        ),
    ]
