# Generated by Django 5.2.8 on 2025-11-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
